# Generated by Django 6.0.3 on 2026-03-19 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countryOfOrigin', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isTrending', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_1_RestarauntApp.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('numGuests', models.IntegerField()),
                ('specialRequests', models.TextField()),
                ('status', models.CharField(choices=[('YE', 'Confirmed'), ('PN', 'Pending'), ('NO', 'Cancelled')], default='PN', max_length=2)),
                ('price', models.IntegerField()),
                ('reservationHolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_1_RestarauntApp.restaurant')),
            ],
        ),
    ]
